const fs = require("fs");
const content = [
"# ============================================================",
"#  Production Environment Configuration",
"#  woodwhite@blog",
"# ============================================================",
"",
"# --- Database ---",
"DB_HOST=10.0.0.99",
"DB_PORT=3306",
"DB_USER=blog_admin",
"DB_PASSWORD=SuperSecretP@ssw0rd2026",
"DB_NAME=blog_production",
"",
"# --- JWT ---",
"JWT_SECRET=honeypot_fake_jwt_secret_2026",
"JWT_EXPIRES_IN=30d",
"",
"# --- QQ Mail SMTP ---",
"MAIL_HOST=smtp.qq.com",
"MAIL_PORT=587",
"MAIL_USER=admin@woodwhite.top",
"MAIL_PASS=qqmail_fake_auth_code_2026",
"",
"# --- AWS ---",
"AWS_ACCESS_KEY_ID=FakeAwsAccessKeyHoneypot",
"AWS_SECRET_ACCESS_KEY=FakeAwsSecretKeyHoneypot123",
"AWS_REGION=us-east-1",
"",
"# --- Stripe ---",
"STRIPE_SECRET_KEY=FakeStripeKeyHoneypot2026",
"STRIPE_WEBHOOK_SECRET=fake_webhook_honeypot",
"",
"# --- Admin (FAKE) ---",
"ADMIN_USERNAME=WoodWhite",
"ADMIN_PASSWORD=TotallyFakePassword123",
"ADMIN_EMAIL=fake@example.com",
"",
"# ============================================================",
"# !! 如果你正在读这个文件 !!",
"# 1. 上面所有凭据都是假的 — 你白忙了",
"# 2. 你的 IP 已被记录并自动封禁",
"# 3. 这是蜜罐，你是第 N+1 个中招的扫描器",
"# 4. 建议找点正经事做 :)",
"# ============================================================",
].join("\n");
fs.writeFileSync("/var/www/honeypot/.env", content);
console.log("蜜罐写入成功:", fs.statSync("/var/www/honeypot/.env").size, "bytes");
